version: "3"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.
    # @see https://symfony.com/doc/current/setup/symfony_server.html#docker-integration
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
